### ISSUE TITLE
Issue after upgrading to 1.8.6

### ISSUE THREAD

**Issue by ajasingh** [langchain-ai/deepagentsjs#384]
My app was working properly till 1.8.5 version today and after ugprading to new version to 1.8.6 i starting getting this error 

data: {"type":"turn_failed","turnId":"a3a4495a-6dd9-4a03-9a58-a97f733a600e","error":"keyValidator._parse is not a function","conversationId":"c9b805c0-e35c-4b44-9d75-579793bea159","timestamp":"2026-03-28T09:33:51.550Z"}

I am not able to locate from where this error is coming from as not exception is getting logged else where

Here is my packge.json

{
  "name": "incident-agent",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "build": "tsc",
    "start": "node dist/service.js",
    "start:aiops": "node dist/aiops-mvp/server.js",
    "ingest": "node dist/ingest.js",
    "ingest:confluence": "node dist/ingestConfluence.js",
    "retrieve": "node dist/retreival.js",
    "verify": "node dist/verify.js",
    "clone": "node dist/Services/changeRequest.js",
    "agent": "node dist/agents/test.js",
    "eval": "node dist/eval.js",
    "test:alert-remediation-tool": "node dist/test/test-alert-remediation-tool.js",
    "test:ai-skills-branch": "node dist/test/test-ai-skills-branch.js",
    "test:deep-skills-live": "node dist/test/test-deep-skills-live.js",
    "test:deep-skills-live-access-request": "node dist/test/test-deep-skills-live-access-request.js",
    "test:config-service": "node dist/test/test-config-service.js",
    "lint": "echo 1",
    "test": "echo 1"
  },
  "dependencies": {
    "@chat-adapter/slack": "4.23.0",
    "@chat-adapter/state-memory": "4.23.0",
    "@chat-adapter/teams": "4.23.0",
    "@hono/node-server": "1.19.11",
    "@langchain/community":"1.1.25",
    "@langchain/core": "1.1.36",
    "@langchain/langgraph-checkpoint-postgres": "1.0.1",
    "@langchain/openai": "1.3.1",
    "axios": "1.12.2",
    "chat": "4.23.0",
    "cloud-config-client": "^1.6.2",
    "deepagents": "1.8.6",
    "hono": "4.10.2",
    "html-to-text": "^9.0.5",
    "langchain": "1.2.37",
    "node-sql-parser": "^4.10.0",
    "oracledb": "^6.10.0",
    "pg": "8.16.3",
    "xlsx": "0.18.5",
    "zod": "^3.25.76"
  },
  "devDependencies": {
    "@types/pg": "^8.15.5",
    "typescript": "5.9.3"
  }
}
